name: newrelic_qa_final_2023-10-19

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (enable or disable)'
        required: true
        default: 'enable'
        options:
          - 'enable'
          - 'disable'

jobs:
  enable-disable-monitor:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Set Node.js version to 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::476057914212:role/github-action-role
          role-session-name: MySessionName

      - name: Get New Relic API key from AWS Secret Manager
        id: secret-manager
        run: |
          secret_value=$(aws secretsmanager get-secret-value --secret-id /ecomm/synthetic-monitor-qa/newrelic-api --query 'SecretString' --output text)
          api_key=$(echo $secret_value | jq -r '.api_key')
          echo "api_key=$api_key" >> $GITHUB_ENV

      - name: Get Slack Webhook URL from AWS Secret Manager
        id: slack-secret-manager
        run: |
          slack_webhook_url=$(aws secretsmanager get-secret-value --secret-id /ecomm/synthetic-monitor-qa/slack_webhook --query 'SecretString' --output text)
          slack_webhook=$(echo $slack_webhook_url | jq -r '.slack_webhook')
          echo "slack_webhook=$slack_webhook" >> $GITHUB_ENV

      - name: List monitors
        id: list-monitors
        run: |
          monitors=$(curl -s -X GET -H "Api-Key:${{ env.api_key }}" \
            "https://synthetics.newrelic.com/synthetics/api/v3/monitors" \
            | jq '[.monitors[] | select(.name | startswith("QA"))]')
          echo "$monitors" > monitors.json

      - name: Enable or Disable Synthetic Monitors
        run: |
          if [ "${{ github.event.inputs.action }}" == "enable" ]; then
            monitors_to_enable=$(cat monitors.json | jq -r '.[] | select(.status == "DISABLED") | .id')
            monitors_to_enable_name=$(cat monitors.json | jq -r '.[] | select(.status == "DISABLED") | .name')
            if [ -n "$monitors_to_enable" ]; then
              for monitor_id in $monitors_to_enable; do
                curl -X PATCH -H "Api-Key:${{ env.api_key }}" \
                  -H 'Content-Type: application/json' \
                  "https://synthetics.newrelic.com/synthetics/api/v3/monitors/$monitor_id" \
                  -d '{ "status" : "enabled" }'
                echo "Synthetic monitor ($monitor_id) enabled."
              done
              message="Enabled monitors:\n$monitors_to_enable_name"
            else
              echo "No disabled monitors to enable."
              message="No disabled monitors to enable."
            fi
          elif [ "${{ github.event.inputs.action }}" == "disable" ]; then
            monitors_to_disable=$(cat monitors.json | jq -r '.[] | select(.status == "ENABLED") | .id')
            monitors_to_disable_name=$(cat monitors.json | jq -r '.[] | select(.status == "ENABLED") | .name')
            if [ -n "$monitors_to_disable" ]; then
              for monitor_id in $monitors_to_disable; do
                curl -X PATCH -H "Api-Key:${{ env.api_key }}" \
                  -H 'Content-Type: application/json' \
                  "https://synthetics.newrelic.com/synthetics/api/v3/monitors/$monitor_id" \
                  -d '{ "status" : "disabled" }'
                echo "Synthetic monitor ($monitor_id) disabled."
              done
              message="Disabled monitors:\n$monitors_to_disable_name"
            else
              echo "No enabled monitors found. Skipping disable action."
              message="No enabled monitors found. Skipping disable action."
            fi
          fi
          echo "$message" > monitors_status.txt

      - name: Notify Slack
        run: |
          monitors_status=$(cat monitors_status.txt)
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$monitors_status\"}" $slack_webhook
